# Generated by Django 4.2.5 on 2023-11-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0002_alter_socio_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='ano_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(max_length=15),
        ),
    ]
