# Generated by Django 4.2.5 on 2023-11-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0003_alter_socio_ano_nacimiento_alter_socio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='ano_nacimiento',
            field=models.DateField(),
        ),
    ]
