# Generated by Django 4.2.5 on 2023-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_socios', '0004_alter_socio_ano_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
